version: 0.2

env:
  variables:
    IMAGE_TAG: "latest"

phases:
  install:
    runtime-versions:
      nodejs: 18
  pre_build:
    commands:
      - echo "Running test script..."
      - bash devops/scripts/run-tests.sh $AWS_ACCOUNT_ID $REGION $ECR_REPO_NAME $IMAGE_TAG
  build:
    commands:
      - echo "Checking Cypress test exit code..."
      - EXIT_CODE=$(cat test-exit-code.txt)
      - if [ "$EXIT_CODE" -ne 0 ]; then echo "Tests failed"; exit 1; fi
artifacts:
  files:
    - report.html
