version: 0.2

env:
  variables:
    IMAGE_TAG: "latest"  
phases:
  install:
    runtime-versions:
      nodejs: 18
  pre_build:
    commands:
      - echo Running tests script...
      - bash devops/scripts/run-tests.sh $AWS_ACCOUNT_ID $REGION $ECR_REPO_NAME $IMAGE_TAG 

artifacts:
  files:
    - report.html

eports:
  CypressReports:
    files:
      - report.html
    base-directory: .
    discard-paths: yes
